### ISSUE TITLE
all sensors unavailable (3.5.2 with HA 2024.8.3)

### ISSUE THREAD

**Issue by haraldbootz** [hultenvp/solis-sensor#384]
All sensors unavailable since yesterday
Soliscloud is working

Solis Integration 3.5.2
HA Core 2024.8.3
HA Supervisor 2024.08.0
HACS 2.0.0

2024-08-29 07:26:06.991 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'solis' calls async_forward_entry_setup for integration, solis with title: Station 1886d7 and entry_id: 3ce74fdc0f97140c6f4c47819e1f5ca6, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/solis/__init__.py, line 94: hass.async_create_task(, 
please create a bug report at https://github.com/hultenvp/solis-sensor/issues

2024-08-29 07:26:06.972 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from solis, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'solis' custom integration
2024-08-29 07:26:06.974 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from solis, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'solis' custom integration
2024-08-29 07:26:06.988 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/solis/workarounds.yaml', 'r') inside the event loop by custom integration 'solis' at custom_components/solis/soliscloud_api.py, line 185: with open('/config/custom_components/solis/workarounds.yaml', 'r') as file: (offender: /config/custom_components/solis/soliscloud_api.py, line 185: with open('/config/custom_components/solis/workarounds.yaml', 'r') as file:), please create a bug report at https://github.com/hultenvp/solis-sensor/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solis/__init__.py", line 82, in async_setup_entry
    portal_config = SoliscloudConfig(
  File "/config/custom_components/solis/soliscloud_api.py", line 185, in __init__
    with open('/config/custom_components/solis/workarounds.yaml', 'r') as file:

**Comment by wiikka** [comment]
Exact same problem started this morning. #383 seems duplicate. Integration doesn't start anymore

```
Lokikirjaaja: custom_components.solis.service
Lähde: custom_components/solis/service.py:116
integraatio: Solis Inverter (dokumentaatio, ongelmat)
Ensimmäistä kertaa ilmennyt: 09.47.37 (3 tapahtumat)
Viimeksi kirjattu: 09.50.43

Failed to discover, scheduling retry in 60 seconds.
Failed to discover, scheduling retry in 120 seconds.
Failed to discover, scheduling retry in 180 seconds.
`````

**Comment by hultenvp** [comment]
The blocking call error has nothing to do with the issue you experience; it's a warning that blocking calls are no longer allowed and the fix is already in the pipeline for release.

What you experience is the SolisCloud backend not responding the way it should. My system is working fine on the same config, so it seems a localized problem on their side. Give it some time and otherwise log a bug with Solis.

**Comment by haraldbootz** [comment]
thankyou hultenvp
